### ISSUE TITLE
Publish SungrowModbusTcpClient to pypi

### ISSUE THREAD

**Issue by tjhowse** [rpvelloso/Sungrow-Modbus#2]
I'd like to integrate this interface into https://github.com/tjhowse/modbus4mqtt without copying the source into my project. A way of doing this would be to add the necessary to this repo to publish it to the Pypi package repo such that it could be installed into a pyenv with pip and imported like any other package.

I'm happy to do the work and raise a PR to add the necessary files to this repo to enable the publish, but I think @rpvelloso will have to be the one to actually do the upload.

**Comment by rpvelloso** [comment]
Bring it on. Let's do this.

**Comment by tjhowse** [comment]
Great! I'll set aside some time this weekend.

**Comment by rpvelloso** [comment]
merged. I'll parameterize the client with the private key, so we don't send the key hard-coded.

**Comment by rpvelloso** [comment]
https://pypi.org/project/SungrowModbusTcpClient/0.1.0/
